CREATE TABLE measurements (
    ME_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ME_DEVICE_ID VARCHAR(50) NOT NULL,
    ME_TIMESTAMP TIMESTAMPTZ NOT NULL,
    ME_METRIC_NAME VARCHAR(100) NOT NULL,
    ME_METRIC_VALUE DOUBLE PRECISION,
    ME_UNIT VARCHAR(20)
);

CREATE INDEX idx_measurements_device_time
    ON measurements (ME_DEVICE_ID, ME_TIMESTAMP DESC);

CREATE INDEX idx_measurements_metric
    ON measurements (ME_METRIC_NAME);
